services:
  postgres:
    container_name: tmi-postgres
    image: 'postgres:16.2'
    hostname: postgres
    environment:
      - 'POSTGRES_DB=demotmi'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
