server:
  port: 9090

spring:
  application:
    name: demo-tmi
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demotmi
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/demotmi
    user: postgres
    password: postgres
    change-log: db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      security.protocol: PLAINTEXT
    consumer:
      auto-offset-reset: latest
      properties:
        allow.auto.create.topics: false
    listener:
      missing-topics-fatal: true

logging:
  level:
    liquibase=DEBUG:
debug: false